location2idx = {
    'move': 0,
    'turnLeft': 1,
    'turnRight': 2,
    'pickMarker': 3,
    'putMarker': 4,
    'while:frontIsClear': 5,
    'while:leftIsClear': 6,
    'while:rightIsClear': 7,
    'while:markersPresent': 8,
    'while:notFrontIsClear': 9,
    'while:notLeftIsClear': 10,
    'while:notRightIsClear': 11,
    'while:noMarkersPresent': 12,
    'repeatUntil:boolGoal': 13,
    'repeat:1': 14,
    'repeat:2': 15,
    'repeat:3': 16,
    'repeat:4': 17,
    'repeat:5': 18,
    'repeat:6': 19,
    'repeat:7': 20,
    'repeat:8': 21,
    'repeat:9': 22,
    'repeat:10': 23,
    'if:frontIsClear': 24,
    'if:leftIsClear': 25,
    'if:rightIsClear': 26,
    'if:markersPresent': 27,
    'if:notFrontIsClear': 28,
    'if:notLeftIsClear': 29,
    'if:notRightIsClear': 30,
    'if:noMarkersPresent': 31,
    'ifElse:frontIsClear': 32,
    'ifElse:leftIsClear': 33,
    'ifElse:rightIsClear': 34,
    'ifElse:markersPresent': 35,
    'ifElse:notFrontIsClear': 36,
    'ifElse:notLeftIsClear': 37,
    'ifElse:notRightIsClear': 38,
    'ifElse:noMarkersPresent': 39,

    'run': 40,
}

idx2location = {v: k for k, v in location2idx.items()}

decision2idx = {
    'binary:0': 0,
    'binary:1': 1,
    'loc:0': 2,
    'loc:1': 3,
    'loc:2': 4,
    'loc:3': 5,
    'loc:4': 6,
    'loc:5': 7,
    'loc:6': 8,
    'loc:7': 9,
    'loc:8': 10,
    'loc:9': 11,
    'loc:10': 12,
    'loc:11': 13,
    'loc:12': 14,
    'loc:13': 15,
    'loc:14': 16,
    'loc:15': 17,
    'loc:16': 18,
    'loc:17': 19,
    'loc:18': 20,
    'loc:19': 21
}

idx2decision = {v: k for k, v in decision2idx.items()}
